import {USER_ROLES} from '../../config/constants';

export const PERMISSIONS = {
  CREATE_BRANCH: 'CREATE_BRANCH',
  MANAGE_BRANCHES: 'MANAGE_BRANCHES',
  MANAGE_BRANCH_USERS: 'MANAGE_BRANCH_USERS',
  MANAGE_ACADEMIC_STRUCTURE: 'MANAGE_ACADEMIC_STRUCTURE',
  ASSIGN_TEACHERS: 'ASSIGN_TEACHERS',
  CORRECT_ATTENDANCE: 'CORRECT_ATTENDANCE',
  MARK_ATTENDANCE: 'MARK_ATTENDANCE',
  VIEW_ATTENDANCE: 'VIEW_ATTENDANCE',
  VIEW_FEES: 'VIEW_FEES',
  MANAGE_FEES: 'MANAGE_FEES',
  UPLOAD_OFFLINE_PAYMENT: 'UPLOAD_OFFLINE_PAYMENT',
  VIEW_FEE_REPORTS: 'VIEW_FEE_REPORTS',
};

const ROLE_PERMISSIONS = {
  [USER_ROLES.MAIN_ADMIN]: [
    PERMISSIONS.CREATE_BRANCH,
    PERMISSIONS.MANAGE_BRANCHES,
    PERMISSIONS.MANAGE_BRANCH_USERS,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.VIEW_FEE_REPORTS,
  ],
  [USER_ROLES.BRANCH_ADMIN]: [
    PERMISSIONS.MANAGE_BRANCH_USERS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.VIEW_FEE_REPORTS,
  ],
  [USER_ROLES.PRINCIPAL]: [
    PERMISSIONS.MANAGE_ACADEMIC_STRUCTURE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.VIEW_FEE_REPORTS,
  ],
  [USER_ROLES.COORDINATOR]: [
    PERMISSIONS.ASSIGN_TEACHERS,
    PERMISSIONS.CORRECT_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_FEES,
  ],
  [USER_ROLES.TEACHER]: [
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_FEES,
  ],
  [USER_ROLES.CLASS_TEACHER]: [
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_FEES,
  ],
  [USER_ROLES.PARENT]: [PERMISSIONS.VIEW_ATTENDANCE, PERMISSIONS.VIEW_FEES],
  [USER_ROLES.ACCOUNTANT]: [
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.MANAGE_FEES,
    PERMISSIONS.UPLOAD_OFFLINE_PAYMENT,
    PERMISSIONS.VIEW_FEE_REPORTS,
  ],
};

export const hasPermission = (role, permission) =>
  Boolean(ROLE_PERMISSIONS[role]?.includes(permission));

export const canEditAttendance = role => role === USER_ROLES.COORDINATOR;
